### ISSUE TITLE
Group By Monthly Challenge?

### ISSUE THREAD

**Issue by joelbyler** [jaegerpicker/CantonSoftwareMentorship#14]
Can we reorganize this to pull each person's submissions into a folder for each month's challenge?  I think over time the current structure will get very cluttered.  I am willing to do the work, just wanted to start the conversation.  Let me know what you think.

**Comment by brandonjoyce** [comment]
I like the idea.

**Comment by davidcollins4481** [comment]
Would probably be best to create the new directory after/during each meeting to prevent having multiple people creating separate ones...conflicts are never fun :)

**Comment by jaegerpicker** [comment]
Our current plan has been to creating a folder for each month and putting each sample from that month in that folder. That being said if you have a better organization in mind I'm all for it. The more people helping/contributing the better. :)

**Comment by jaegerpicker** [comment]
I'll merge the pull requests with it if it's submitted.

**Comment by brandonjoyce** [comment]
Ah, ya I like the monthly idea better.

**Comment by joelbyler** [comment]
Done, see pull request submitted this afternoon.  Perhaps we can also update the readme to instruct others on how to add the upstream remote and pull / merge from upstream?

**Comment by jaegerpicker** [comment]
Pull request merged and the README.md files updated. I'll be sending out the RomanNumeral challenge email later tonight. I've added the git fork and pull request instructions to the README.md files.
